controller:
  kind: DaemonSet
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  service:
    type: ClusterIP
  nodeSelector:
    ingress-ready: "true"
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      effect: NoSchedule
  publishService:
    enabled: false
  watchIngressWithoutClass: true
  ingressClassResource:
    default: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: observability
      additionalLabels:
        release: kps
